version: "2.1"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=belajar
      - MYSQL_USER=belajar
      - MYSQL_PASSWORD=java
    volumes:
      #      - /opt/data:/var/lib/mysql
      - /tmp/data/mysql:/var/lib/mysql

  belajarci-app:
    image: hendisantika/docker-workflow-4-springboot-developer
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    ports:
    - 80:8080