version: "3"

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=belajar
      - MYSQL_USER=belajar
      - MYSQL_PASSWORD=java
    volumes:
      #      - /opt/data:/var/lib/mysql
      #      - /tmp/data/mysql:/var/lib/mysql
      - /data/mysql
  springboot-container:
    image: hendisantika/docker-workflow-4-springboot-developer
    environment:
      #      - SPRING_PROFILES_ACTIVE=default
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/springboot-container